### ISSUE TITLE
Provide a "First Class" API for Lua Scripting

### ISSUE THREAD

**Issue by Mordil** [Mordil/RediStack#44]
I'm opening this up for discussion of what people may want to do with Lua scripting integration through the Swift client against Redis.

The list of supported commands: https://redis.io/commands#scripting

**Comment by vegiwoo** [comment]
I encountered the following scenario - in Redis I create geosets added by GEOADD, besides there are user attention zones (added by ZADD [geoset] 0 user: {id}: att_zone) and event location locations (added by ZADD [geoset] 0 activity: {id}: location). When adding a new event on ZRANGE [geoset] 0 -1I get all the entities of this geostet and filter only the attention zones (user: {id}: att_zone), then for each found attention zone I want to perform GEORADIUS [geoset] [attention zone] [radius] km to see if the event created is in the attention zone of a specific user, and if so, I inform the user about a new event in his attention zone. In Swift code, this is quite a complex call chain for me and I would like to try writing a script for this task.
