### ISSUE TITLE
about the dependency url

### ISSUE THREAD

**Issue by micezhao** [Mordil/RediStack#49]
Today's afternoon, I tried to integrate the Redis to vapor 4 (my swift version is 5.4)

according to this doc , I copied the url ( .package(url: "https://gitlab.com/mordil/RediStack.git", .branch("master"))) to my Package.swift 

but the complier reported an unwanted problem, it indicated  :" https://gitlab.com/Mordil/RediStack: An unknown error occurred. unexpected return value from ssl handshake -9806 (-1)"

Meanwhile, I found another reference on vapor's doc (https://docs.vapor.codes/4.0/redis/overview/). Unfortunately, it was also unable to be fixed. 

Finally, I attempted to substitute the "gitlab" by "github", then the dependency package can be install on my app

To be honesty, I had spent more to an hour to address this issue. so , would you mind to change the url into the right way ?

**Comment by 0xTim** [comment]
@micezhao The RediStack package is hosted on Gitlab as that's where the development is done - this repo is just a mirror. Can you clone the package directly from Gitlab?

**Comment by micezhao** [comment]
> @micezhao The RediStack package is hosted on Gitlab as that's where the development is done - this repo is just a mirror. Can you clone the package directly from Gitlab?

No! I have tried several times by fetching this dependency directly.Whereas, The complier did not resolved the package info correctly. 
Actually , even if  the dependency can be fetched with url in GitHub and resolved normally in Xcode.However , I still have no idea of how use this in vapor ,  not like in Java with Spring-Framework.

<img width="1533" alt="截屏2021-05-19 06 03 24" src="https://user-images.githubusercontent.com/18138143/118729189-0e3e3700-b868-11eb-927e-47b9c8d4aaa9.png">

**Comment by Mordil** [comment]
This looks like standard SSL errors.

Are you able to vie the GitLab repo in a browser?

also, what does your Package.swift look like?

**Comment by micezhao** [comment]
ok~ the following picture is my content
<img width="1232" alt="截屏2021-05-19 09 44 46" src="https://user-images.githubusercontent.com/18138143/118744534-13f74500-b887-11eb-8384-1e6560903e6b.png">

**Comment by Mordil** [comment]
Ok, 2 problems:

1) The product and package names are case sensitive so it should be `RediStack` for both
2) the latest `Master` has breaking changes that are incompatible with Vapor right now unless you intend to do all the glue code yourself.

it is recommended to use the Vapor/Redis v4 package to gain Vapor+Redis features

**Comment by micezhao** [comment]
@Mordil 
OK, I have addressed this problem according to your method !
 thanks 😊
